name: 'sign in Bot'
 
on:
  watch:
    types: started
  schedule:
  # 定时任务，在每天的5点推送登录信息到钉钉
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
jobs:
  bot:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Set up Python
      uses: actions/setup-python@v3

      with:

       python-version: '3.x'

      # 安装依赖

    - name: Install dependencies

      run: |

       python -m pip install --upgrade pip

       pip install requests
    - name: Update paper list
      run: |
        python qd.py ${{ secrets.username }} ${{ secrets.password }} ${{ secrets.answer }} ${{ secrets.dingtalk_token }} 
